services:
  - type: web
    name: bad-telegram-bot-cz
    runtime: node
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: VOICEFLOW_API_KEY
        sync: false
      - key: VOICEFLOW_VERSION_ID
        sync: false
